services:
  rosemary_admin:
    container_name: rose_admin
    # restart: unless-stopped
    build:
      context: ./admin
      dockerfile: Dockerfile
    networks:
      - rosemary_network
    ports:
      - 5173:5173
    develop:
      watch:
        - action: sync
          path: ./admin
          target: /app
  rosemary_server:
    container_name: rose_server
    # restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3030:3030
    networks:
      - rosemary_network
    volumes:
      - ./src/certs:/app/certs
      - ./.env.dev:/app/.env
      - ./static/www:/app/www/static
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app
        - action: rebuild
          path: ./templates
          target: /app
  rosemary_proxy:
    depends_on:
      - rosemary_admin
      - rosemary_server
    container_name: rose_proxy
    image: nginx:latest
    # restart: unless-stopped
    volumes:
      - ./static/:/usr/share/nginx/html/static
      - ./development/nginx:/var/log/nginx
      - ./development/nginx/nginx_compose.conf:/etc/nginx/nginx.conf
    networks:
      - rosemary_network
    ports:
      - 80:80
    develop:
      watch:
        - action: sync+restart
          path: ./development/nginx/nginx_compose.conf
          target: /etc/nginx/nginx.conf

networks:
  rosemary_network:
    driver: bridge